-- DEPRECATED REDIRECT STUB - DO NOT USE AS ACTIVE MIGRATION.
-- The early Phase 1 schema skeleton has been archived at:
-- docs/supabase-historical-schema-skeleton.md
--
-- Current Supabase restaurant-platform schema review baseline lives in:
-- docs/supabase-schema-mapping.md
-- docs/supabase-schema-drafts/*.sql
-- docs/supabase-schema-decision-register.md
-- docs/supabase-schema-freeze-manifest.md
--
-- This file intentionally contains no executable SQL.
