export const TEMPORAL_PREVIEW_RPC="restaurant_owner_preview_branch_temporal_v1" as const;
export const TEMPORAL_WEEKLY_RPC="restaurant_owner_replace_branch_weekly_hours_v1" as const;
export const TEMPORAL_SPECIAL_RPC="restaurant_owner_set_branch_special_hours_v1" as const;
export const TEMPORAL_CLOSE_NOW_RPC="restaurant_owner_close_branch_now_v1" as const;
export const TEMPORAL_SCHEDULE_RPC="restaurant_owner_schedule_branch_closure_v1" as const;
export const TEMPORAL_REOPEN_RPC="restaurant_owner_reopen_branch_now_v1" as const;
export const TEMPORAL_CANCEL_RPC="restaurant_owner_cancel_future_branch_closure_v1" as const;
export type Failure="unauthenticated"|"permission_denied"|"invalid_request"|"target_not_found"|"stale_state"|"no_change"|"lifecycle_blocked"|"invalid_local_time"|"closure_conflict"|"dependency_unavailable"|"internal_failure";
export type Interval=Readonly<{startLocalTime:string;endLocalTime:string;endDayOffset:0|1}>;
export type WeeklyInterval=Interval&Readonly<{weekday:1|2|3|4|5|6|7}>;
export type SpecialOverride=Readonly<{localDate:string;mode:"closed"|"custom";intervals:readonly Interval[]}>;
export type Closure=Readonly<{closureId:string;startsAt:string;endsAt:string|null}>;
export type Preview={ok:true;state:"ready";branchId:string;timezone:string;weeklyHoursConfigured:boolean;weeklyHours:readonly WeeklyInterval[];weeklyHoursVersion:string;specialOverrides:readonly SpecialOverride[];specialHoursVersion:string;operationalClosures:readonly Closure[];operationalClosureVersion:string;currentState:"OPEN"|"CLOSED"|"UNKNOWN";currentReason:string}|{state:Failure};
export type WeeklyInput=Readonly<{operation:"REPLACE_WEEKLY_SCHEDULE";intervals:readonly WeeklyInterval[];expectedVersion:string}|{operation:"CLEAR_WEEKLY_SCHEDULE";expectedVersion:string}>;
export type SpecialInput=Readonly<{localDate:string;operation:"SET_CLOSED";expectedVersion:string}|{localDate:string;operation:"SET_CUSTOM_HOURS";intervals:readonly Interval[];expectedVersion:string}|{localDate:string;operation:"CLEAR_OVERRIDE";expectedVersion:string}>;
export type ClosureInput=Readonly<{operation:"CLOSE_NOW_INDEFINITE";expectedVersion:string}|{operation:"CLOSE_NOW_UNTIL";untilLocalDateTime:string;fold:"earlier"|"later"|null;expectedVersion:string}|{operation:"SCHEDULE_CLOSURE";startLocalDateTime:string;startFold:"earlier"|"later"|null;endLocalDateTime:string|null;endFold:"earlier"|"later"|null;expectedVersion:string}|{operation:"REOPEN_NOW";closureId:string;expectedVersion:string}|{operation:"CANCEL_FUTURE_CLOSURE";closureId:string;expectedVersion:string}>;
export type WeeklyMutation={ok:true;state:"applied";branchId:string;weeklyHoursConfigured:boolean;weeklyHours:readonly WeeklyInterval[];weeklyHoursVersion:string}|{state:Failure};
export type SpecialMutation={ok:true;state:"applied";branchId:string;localDate:string;mode:"closed"|"custom"|null;intervals:readonly Interval[];specialHoursVersion:string}|{state:Failure};
export type ClosureMutation={ok:true;state:"applied";branchId:string;closureId:string;startsAt:string;endsAt:string|null;operationalClosureVersion:string}|{ok:true;state:"applied";branchId:string;closureId:string;endsAt:string;operationalClosureVersion:string}|{ok:true;state:"applied";branchId:string;closureId:string;cancelledAt:string;operationalClosureVersion:string}|{state:Failure};
export type Mutation=WeeklyMutation|SpecialMutation|ClosureMutation;
export const isRecord=(v:unknown):v is Record<string,unknown>=>typeof v==="object"&&v!==null&&!Array.isArray(v);const exact=(v:Record<string,unknown>,k:string[])=>JSON.stringify(Object.keys(v).sort())===JSON.stringify([...k].sort());
export const isVersion=(v:unknown):v is string=>typeof v==="string"&&/^(0|[1-9][0-9]{0,18})$/.test(v);export const readId=(v:unknown)=>typeof v==="string"&&/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/.test(v)?v:null;const uuid=(v:unknown):v is string=>typeof v==="string"&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v);const date=(v:unknown):v is string=>typeof v==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(v);const localDateTime=(v:unknown):v is string=>typeof v==="string"&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(?::\d{2})?$/.test(v);const instant=(v:unknown):v is string=>typeof v==="string"&&Number.isFinite(Date.parse(v));const time=(v:unknown):v is string=>typeof v==="string"&&/^\d{2}:\d{2}:\d{2}$/.test(v);
export function parseInterval(v:unknown):Interval|null{if(!isRecord(v))return null;const startLocalTime=v.startLocalTime,endLocalTime=v.endLocalTime,endDayOffset=v.endDayOffset;if(!exact(v,["startLocalTime","endLocalTime","endDayOffset"])||!time(startLocalTime)||!time(endLocalTime)||(endDayOffset!==0&&endDayOffset!==1))return null;const ok=endDayOffset===0?startLocalTime<endLocalTime:startLocalTime>endLocalTime||(startLocalTime==="00:00:00"&&endLocalTime==="00:00:00");return ok?{startLocalTime,endLocalTime,endDayOffset}:null;}
export function parseWeeklyInterval(v:unknown):WeeklyInterval|null{if(!isRecord(v))return null;const weekday=v.weekday;if(!exact(v,["weekday","startLocalTime","endLocalTime","endDayOffset"])||!Number.isInteger(weekday)||(weekday as number)<1||(weekday as number)>7)return null;const x=parseInterval({startLocalTime:v.startLocalTime,endLocalTime:v.endLocalTime,endDayOffset:v.endDayOffset});return x?{weekday:weekday as WeeklyInterval["weekday"],...x}:null;}
const intervals=(v:unknown,weekly=false)=>{if(!Array.isArray(v)||v.length>56)return null;const parsed=v.map(x=>weekly?parseWeeklyInterval(x):parseInterval(x));return parsed.some(x=>x===null)?null:Object.freeze(parsed as (WeeklyInterval|Interval)[]);};
const error=(v:Record<string,unknown>):Failure|null=>exact(v,["ok","errorCode"])&&v.ok===false&&typeof v.errorCode==="string"&&["unauthenticated","permission_denied","invalid_request","target_not_found","stale_state","no_change","lifecycle_blocked","invalid_local_time","closure_conflict"].includes(v.errorCode)?v.errorCode as Failure:null;
export function parsePreview(v:unknown):Preview|null{if(!isRecord(v))return null;const e=error(v);if(e)return{state:e};
  const branchId=readId(v.branchId),timezone=v.timezone,weeklyHoursConfigured=v.weeklyHoursConfigured,weeklyHoursVersion=v.weeklyHoursVersion,specialOverridesRaw=v.specialOverrides,specialHoursVersion=v.specialHoursVersion,operationalClosuresRaw=v.operationalClosures,operationalClosureVersion=v.operationalClosureVersion,currentState=v.currentState,currentReason=v.currentReason;
  if(!exact(v,["ok","state","branchId","timezone","weeklyHoursConfigured","weeklyHours","weeklyHoursVersion","specialOverrides","specialHoursVersion","operationalClosures","operationalClosureVersion","currentState","currentReason"])||v.ok!==true||v.state!=="ready"||!branchId||typeof timezone!=="string"||typeof weeklyHoursConfigured!=="boolean"||!isVersion(weeklyHoursVersion)||!isVersion(specialHoursVersion)||!isVersion(operationalClosureVersion)||!["OPEN","CLOSED","UNKNOWN"].includes(String(currentState))||typeof currentReason!=="string")return null;
  const w=intervals(v.weeklyHours,true);if(!w||!Array.isArray(specialOverridesRaw)||!Array.isArray(operationalClosuresRaw))return null;
  const s=specialOverridesRaw.map(x=>{if(!isRecord(x))return null;const localDate=x.localDate,mode=x.mode,intervalsRaw=x.intervals;if(!exact(x,["localDate","mode","intervals"])||!date(localDate)||!(mode==="closed"||mode==="custom"))return null;return{localDate,mode,intervals:intervals(intervalsRaw)??null};});
  const c=operationalClosuresRaw.map(x=>{if(!isRecord(x))return null;const closureId=x.closureId,startsAt=x.startsAt,endsAt=x.endsAt;if(!exact(x,["closureId","startsAt","endsAt"])||!uuid(closureId)||!instant(startsAt)||(endsAt!==null&&!instant(endsAt)))return null;return{closureId,startsAt,endsAt};});
  if(s.some(x=>!x||!x.intervals)||c.some(x=>!x))return null;
  return{ok:true,state:"ready",branchId,timezone,weeklyHoursConfigured,weeklyHours:w as readonly WeeklyInterval[],weeklyHoursVersion,specialOverrides:s as SpecialOverride[],specialHoursVersion,operationalClosures:c as Closure[],operationalClosureVersion,currentState:currentState as "OPEN"|"CLOSED"|"UNKNOWN",currentReason};}
// Exact per-operation success parsers for the raw P1 mutation RPC results. Each requires the exact
// key set P1 actually returns (see supabase/migrations/20260906030000_...sql), validates auditId's
// presence/type, then withholds it from the object returned to the browser.
export function parseWeeklyMutation(v:unknown):WeeklyMutation|null{if(!isRecord(v))return null;const e=error(v);if(e)return{state:e};const branchId=readId(v.branchId),weeklyHoursConfigured=v.weeklyHoursConfigured,weeklyHoursVersion=v.weeklyHoursVersion,auditId=v.auditId;if(!exact(v,["ok","state","branchId","weeklyHoursConfigured","weeklyHours","weeklyHoursVersion","auditId"])||v.ok!==true||v.state!=="applied"||!branchId||typeof weeklyHoursConfigured!=="boolean"||!isVersion(weeklyHoursVersion)||typeof auditId!=="string")return null;const w=intervals(v.weeklyHours,true);if(!w)return null;return{ok:true,state:"applied",branchId,weeklyHoursConfigured,weeklyHours:w as readonly WeeklyInterval[],weeklyHoursVersion};}
export function parseSpecialMutation(v:unknown):SpecialMutation|null{if(!isRecord(v))return null;const e=error(v);if(e)return{state:e};const branchId=readId(v.branchId),localDate=v.localDate,mode=v.mode,specialHoursVersion=v.specialHoursVersion,auditId=v.auditId;if(!exact(v,["ok","state","branchId","localDate","mode","intervals","specialHoursVersion","auditId"])||v.ok!==true||v.state!=="applied"||!branchId||!date(localDate)||!(mode===null||mode==="closed"||mode==="custom")||!isVersion(specialHoursVersion)||typeof auditId!=="string")return null;const iv=intervals(v.intervals);if(!iv)return null;return{ok:true,state:"applied",branchId,localDate,mode,intervals:iv,specialHoursVersion};}
export function parseClosureWindowMutation(v:unknown):ClosureMutation|null{if(!isRecord(v))return null;const e=error(v);if(e)return{state:e};const branchId=readId(v.branchId),closureId=v.closureId,startsAt=v.startsAt,endsAt=v.endsAt,operationalClosureVersion=v.operationalClosureVersion,auditId=v.auditId;if(!exact(v,["ok","state","branchId","closureId","startsAt","endsAt","operationalClosureVersion","auditId"])||v.ok!==true||v.state!=="applied"||!branchId||!uuid(closureId)||!instant(startsAt)||(endsAt!==null&&!instant(endsAt))||!isVersion(operationalClosureVersion)||typeof auditId!=="string")return null;return{ok:true,state:"applied",branchId,closureId,startsAt,endsAt,operationalClosureVersion};}
export function parseReopenMutation(v:unknown):ClosureMutation|null{if(!isRecord(v))return null;const e=error(v);if(e)return{state:e};const branchId=readId(v.branchId),closureId=v.closureId,endsAt=v.endsAt,operationalClosureVersion=v.operationalClosureVersion,auditId=v.auditId;if(!exact(v,["ok","state","branchId","closureId","endsAt","operationalClosureVersion","auditId"])||v.ok!==true||v.state!=="applied"||!branchId||!uuid(closureId)||!instant(endsAt)||!isVersion(operationalClosureVersion)||typeof auditId!=="string")return null;return{ok:true,state:"applied",branchId,closureId,endsAt,operationalClosureVersion};}
export function parseCancelMutation(v:unknown):ClosureMutation|null{if(!isRecord(v))return null;const e=error(v);if(e)return{state:e};const branchId=readId(v.branchId),closureId=v.closureId,cancelledAt=v.cancelledAt,operationalClosureVersion=v.operationalClosureVersion,auditId=v.auditId;if(!exact(v,["ok","state","branchId","closureId","cancelledAt","operationalClosureVersion","auditId"])||v.ok!==true||v.state!=="applied"||!branchId||!uuid(closureId)||!instant(cancelledAt)||!isVersion(operationalClosureVersion)||typeof auditId!=="string")return null;return{ok:true,state:"applied",branchId,closureId,cancelledAt,operationalClosureVersion};}
// Client-side wire parsers: validate the ALREADY-STRIPPED shape our OWN server sends (auditId
// withheld, no raw RPC fields) -- deliberately distinct from the raw-RPC parsers above, which
// require auditId to be present so the server can prove it validated before withholding it.
export function parseWeeklyMutationWire(v:unknown):WeeklyMutation|null{if(!isRecord(v))return null;const e=error(v);if(e)return{state:e};const branchId=readId(v.branchId),weeklyHoursConfigured=v.weeklyHoursConfigured,weeklyHoursVersion=v.weeklyHoursVersion;if(!exact(v,["ok","state","branchId","weeklyHoursConfigured","weeklyHours","weeklyHoursVersion"])||v.ok!==true||v.state!=="applied"||!branchId||typeof weeklyHoursConfigured!=="boolean"||!isVersion(weeklyHoursVersion))return null;const w=intervals(v.weeklyHours,true);if(!w)return null;return{ok:true,state:"applied",branchId,weeklyHoursConfigured,weeklyHours:w as readonly WeeklyInterval[],weeklyHoursVersion};}
export function parseSpecialMutationWire(v:unknown):SpecialMutation|null{if(!isRecord(v))return null;const e=error(v);if(e)return{state:e};const branchId=readId(v.branchId),localDate=v.localDate,mode=v.mode,specialHoursVersion=v.specialHoursVersion;if(!exact(v,["ok","state","branchId","localDate","mode","intervals","specialHoursVersion"])||v.ok!==true||v.state!=="applied"||!branchId||!date(localDate)||!(mode===null||mode==="closed"||mode==="custom")||!isVersion(specialHoursVersion))return null;const iv=intervals(v.intervals);if(!iv)return null;return{ok:true,state:"applied",branchId,localDate,mode,intervals:iv,specialHoursVersion};}
export function parseClosureMutationWire(v:unknown):ClosureMutation|null{if(!isRecord(v))return null;const e=error(v);if(e)return{state:e};const branchId=readId(v.branchId),closureId=v.closureId,operationalClosureVersion=v.operationalClosureVersion;if(!branchId||!uuid(closureId)||v.ok!==true||v.state!=="applied"||!isVersion(operationalClosureVersion))return null;const startsAt=v.startsAt,endsAt=v.endsAt,cancelledAt=v.cancelledAt;if(exact(v,["ok","state","branchId","closureId","startsAt","endsAt","operationalClosureVersion"])&&instant(startsAt)&&(endsAt===null||instant(endsAt)))return{ok:true,state:"applied",branchId,closureId,startsAt,endsAt,operationalClosureVersion};if(exact(v,["ok","state","branchId","closureId","endsAt","operationalClosureVersion"])&&instant(endsAt))return{ok:true,state:"applied",branchId,closureId,endsAt,operationalClosureVersion};if(exact(v,["ok","state","branchId","closureId","cancelledAt","operationalClosureVersion"])&&instant(cancelledAt))return{ok:true,state:"applied",branchId,closureId,cancelledAt,operationalClosureVersion};return null;}
export function parseWeeklyInput(v:unknown):WeeklyInput|null{if(!isRecord(v)||!isVersion(v.expectedVersion)||typeof v.operation!=="string")return null;if(v.operation==="CLEAR_WEEKLY_SCHEDULE"&&exact(v,["operation","expectedVersion"]))return{operation:v.operation,expectedVersion:v.expectedVersion};const x=intervals(v.intervals,true);return v.operation==="REPLACE_WEEKLY_SCHEDULE"&&exact(v,["operation","intervals","expectedVersion"])&&x?{operation:v.operation,intervals:x as WeeklyInterval[],expectedVersion:v.expectedVersion}:null;}
export function parseSpecialInput(v:unknown):SpecialInput|null{if(!isRecord(v)||!date(v.localDate)||!isVersion(v.expectedVersion)||typeof v.operation!=="string")return null;if((v.operation==="SET_CLOSED"||v.operation==="CLEAR_OVERRIDE")&&exact(v,["localDate","operation","expectedVersion"]))return{localDate:v.localDate,operation:v.operation,expectedVersion:v.expectedVersion} as SpecialInput;const x=intervals(v.intervals);return v.operation==="SET_CUSTOM_HOURS"&&exact(v,["localDate","operation","intervals","expectedVersion"])&&x&&x.length>0&&x.length<=8?{localDate:v.localDate,operation:v.operation,intervals:x,expectedVersion:v.expectedVersion}:null;}
export function parseClosureInput(v:unknown):ClosureInput|null{if(!isRecord(v)||!isVersion(v.expectedVersion)||typeof v.operation!=="string")return null;if(v.operation==="CLOSE_NOW_INDEFINITE"&&exact(v,["operation","expectedVersion"]))return{operation:v.operation,expectedVersion:v.expectedVersion};if(v.operation==="CLOSE_NOW_UNTIL"&&exact(v,["operation","untilLocalDateTime","fold","expectedVersion"])&&localDateTime(v.untilLocalDateTime)&&(v.fold===null||v.fold==="earlier"||v.fold==="later"))return{operation:v.operation,untilLocalDateTime:v.untilLocalDateTime,fold:v.fold,expectedVersion:v.expectedVersion};if(v.operation==="SCHEDULE_CLOSURE"&&exact(v,["operation","startLocalDateTime","startFold","endLocalDateTime","endFold","expectedVersion"])&&localDateTime(v.startLocalDateTime)&&(v.startFold===null||v.startFold==="earlier"||v.startFold==="later")&&(v.endLocalDateTime===null||localDateTime(v.endLocalDateTime))&&(v.endFold===null||v.endFold==="earlier"||v.endFold==="later"))return{operation:v.operation,startLocalDateTime:v.startLocalDateTime,startFold:v.startFold,endLocalDateTime:v.endLocalDateTime,endFold:v.endFold,expectedVersion:v.expectedVersion};if((v.operation==="REOPEN_NOW"||v.operation==="CANCEL_FUTURE_CLOSURE")&&exact(v,["operation","closureId","expectedVersion"])&&uuid(v.closureId))return{operation:v.operation,closureId:v.closureId,expectedVersion:v.expectedVersion} as ClosureInput;return null;}
export const isoWeekday=(date:Date):WeeklyInterval["weekday"]=>((date.getUTCDay()+6)%7+1) as WeeklyInterval["weekday"];
