import "server-only";
import { getVerifiedRestaurantClaims } from "../auth/supabase-server";
import { getRestaurantDataSourceConfig } from "../config/restaurant-data-source";
import { createRestaurantOwnerPriceRepository } from "../repositories/supabase/restaurant-owner-price-repository";
import { loadRestaurantAccessContext } from "../runtime/restaurant-access-context";
import { RESTAURANT_OWNER_PRICE_BODY_LIMIT, parseMutationRequest, readBoundedIdentity, type RestaurantOwnerPriceMutationResult, type RestaurantOwnerPricePreview } from "../runtime/restaurant-owner-price";
const headers={"Cache-Control":"private, no-store",Vary:"Cookie","X-Content-Type-Options":"nosniff"} as const;
type Result=RestaurantOwnerPricePreview|RestaurantOwnerPriceMutationResult;
const status=(state:Result["state"])=>({ready:200,unauthenticated:401,permission_denied:403,invalid_request:400,target_not_found:404,stale_state:409,no_change:422,dependency_unavailable:503,internal_failure:500}[state]);
const json=(result:Result)=>Response.json(result,{status:status(result.state),headers});
async function identity():Promise<"verified"|"unauthenticated"|"dependency_unavailable"> { if(getRestaurantDataSourceConfig().dataSource!=="supabase") return "dependency_unavailable"; try{return await getVerifiedRestaurantClaims()?"verified":"unauthenticated";}catch{return "dependency_unavailable";} }
async function body(request:Request):Promise<unknown|null>{ const length=request.headers.get("content-length"); if(length!==null&&(!/^[0-9]+$/.test(length)||Number(length)>RESTAURANT_OWNER_PRICE_BODY_LIMIT))return null; if(request.headers.get("content-type")?.split(";",1)[0].trim().toLowerCase()!=="application/json")return null; try{const data=await request.text();if(new TextEncoder().encode(data).byteLength>RESTAURANT_OWNER_PRICE_BODY_LIMIT)return null;return JSON.parse(data);}catch{return null;} }
export async function handleRestaurantOwnerPricePreviewRequest(request:Request,branchInput:unknown,itemInput:unknown):Promise<Response>{ if([...new URL(request.url).searchParams.keys()].length)return json({state:"invalid_request"});const branchId=readBoundedIdentity(branchInput),branchMenuItemId=readBoundedIdentity(itemInput);if(!branchId||!branchMenuItemId)return json({state:"invalid_request"});const verified=await identity();if(verified!=="verified")return json({state:verified});let access;try{access=await loadRestaurantAccessContext();}catch{return json({state:"dependency_unavailable"});}if(access.state==="missing-identity")return json({state:"unauthenticated"});if(access.state!=="selected")return json({state:"permission_denied"});try{const result=await createRestaurantOwnerPriceRepository().preview(access.restaurant.id,branchId,branchMenuItemId);return result.state==="ready"&&(result.branchId!==branchId||result.branchMenuItemId!==branchMenuItemId)?json({state:"internal_failure"}):json(result);}catch{return json({state:"dependency_unavailable"});}}
export async function handleRestaurantOwnerPriceMutationRequest(request:Request,branchInput:unknown,itemInput:unknown):Promise<Response>{ if([...new URL(request.url).searchParams.keys()].length)return json({state:"invalid_request"});const branchId=readBoundedIdentity(branchInput),branchMenuItemId=readBoundedIdentity(itemInput);if(!branchId||!branchMenuItemId)return json({state:"invalid_request"});const verified=await identity();if(verified!=="verified")return json({state:verified});const input=parseMutationRequest(await body(request));if(!input)return json({state:"invalid_request"});try{const result=await createRestaurantOwnerPriceRepository().mutate(branchMenuItemId,input);return result.state==="ready"&&result.branchMenuItemId!==branchMenuItemId?json({state:"internal_failure"}):json(result);}catch{return json({state:"dependency_unavailable"});}}
