import"server-only";import{getVerifiedRestaurantClaims}from"../auth/supabase-server";import{getRestaurantDataSourceConfig}from"../config/restaurant-data-source";import{createRestaurantOwnerBranchTemporalRepository}from"../repositories/supabase/restaurant-owner-branch-temporal-repository";import{loadRestaurantAccessContext}from"../runtime/restaurant-access-context";import{parseCancelMutation,parseClosureInput,parseClosureWindowMutation,parsePreview,parseReopenMutation,parseSpecialInput,parseSpecialMutation,parseWeeklyInput,parseWeeklyMutation,readId,type ClosureInput,type ClosureMutation,type Preview,type SpecialInput,type SpecialMutation,type WeeklyInput,type WeeklyMutation}from"../runtime/restaurant-owner-branch-temporal";type R=Preview|WeeklyMutation|SpecialMutation|ClosureMutation;const headers={"Cache-Control":"private, no-store",Vary:"Cookie","X-Content-Type-Options":"nosniff"}as const;const status:Record<string,number>={ready:200,applied:200,unauthenticated:401,permission_denied:403,invalid_request:400,target_not_found:404,stale_state:409,no_change:422,lifecycle_blocked:403,invalid_local_time:400,closure_conflict:409,dependency_unavailable:503,internal_failure:500};const json=(r:R)=>Response.json(r,{status:status[r.state],headers});async function access(){if(getRestaurantDataSourceConfig().dataSource!=="supabase")return null;try{if(!await getVerifiedRestaurantClaims())return null;const a=await loadRestaurantAccessContext();return a.state==="selected"?a:null}catch{return null}}async function body(r:Request){if(r.headers.get("content-type")?.split(";",1)[0].trim().toLowerCase()!=="application/json")return null;try{return JSON.parse(await r.text())}catch{return null}}
export async function previewBranchTemporal(r:Request,branchRaw:unknown){const branch=readId(branchRaw);if(new URL(r.url).search||!branch)return json({state:"invalid_request"});const a=await access();if(!a)return json({state:"unauthenticated"});try{const p=parsePreview(await createRestaurantOwnerBranchTemporalRepository().preview(a.restaurant.id,branch));if(!p||p.state!=="ready"||p.branchId!==branch)return json({state:(p&&p.state!=="ready"?p.state:"internal_failure")});return json(p)}catch{return json({state:"dependency_unavailable"})}}
// Each mutation family gets its OWN exact P1 success-shape parser (see restaurant-owner-branch-
// temporal.ts) -- weekly and special each have one shape; closure has three (close/schedule share
// one shape; reopen and cancel each have their own), selected by the already-parsed operation. A raw
// RPC result that does not match its family's exact key set is internal_failure, never passed
// through -- this is what stops a real DB success from silently becoming a malformed browser DTO.
async function mutateWeekly(r:Request,branchRaw:unknown){const branch=readId(branchRaw);if(new URL(r.url).search||!branch)return json({state:"invalid_request"});const x=parseWeeklyInput(await body(r)) as WeeklyInput|null;if(!x)return json({state:"invalid_request"});const a=await access();if(!a)return json({state:"unauthenticated"});try{const raw=await createRestaurantOwnerBranchTemporalRepository().weekly(a.restaurant.id,branch,x);const p=parseWeeklyMutation(raw);if(!p)return json({state:"internal_failure"});if(p.state!=="applied")return json(p);if(p.branchId!==branch)return json({state:"internal_failure"});return json(p)}catch{return json({state:"dependency_unavailable"})}}
async function mutateSpecial(r:Request,branchRaw:unknown){const branch=readId(branchRaw);if(new URL(r.url).search||!branch)return json({state:"invalid_request"});const x=parseSpecialInput(await body(r)) as SpecialInput|null;if(!x)return json({state:"invalid_request"});const a=await access();if(!a)return json({state:"unauthenticated"});try{const raw=await createRestaurantOwnerBranchTemporalRepository().special(a.restaurant.id,branch,x);const p=parseSpecialMutation(raw);if(!p)return json({state:"internal_failure"});if(p.state!=="applied")return json(p);if(p.branchId!==branch)return json({state:"internal_failure"});return json(p)}catch{return json({state:"dependency_unavailable"})}}
async function mutateClosure(r:Request,branchRaw:unknown){const branch=readId(branchRaw);if(new URL(r.url).search||!branch)return json({state:"invalid_request"});const x=parseClosureInput(await body(r)) as ClosureInput|null;if(!x)return json({state:"invalid_request"});const a=await access();if(!a)return json({state:"unauthenticated"});try{const raw=await createRestaurantOwnerBranchTemporalRepository().closure(a.restaurant.id,branch,x);const parser=x.operation==="REOPEN_NOW"?parseReopenMutation:x.operation==="CANCEL_FUTURE_CLOSURE"?parseCancelMutation:parseClosureWindowMutation;const p=parser(raw);if(!p)return json({state:"internal_failure"});if(p.state!=="applied")return json(p);if(p.branchId!==branch)return json({state:"internal_failure"});return json(p)}catch{return json({state:"dependency_unavailable"})}}
export const mutateWeeklyTemporal=(r:Request,b:unknown)=>mutateWeekly(r,b);export const mutateSpecialTemporal=(r:Request,b:unknown)=>mutateSpecial(r,b);export const mutateClosureTemporal=(r:Request,b:unknown)=>mutateClosure(r,b);
