-- SR-2C-R1: canonical V1 interest catalog data.
--
-- Catalog CONTENT, deliberately separate from catalog STRUCTURE. Adding an option later is another
-- INSERT here — never a new enum value, a Social core rewrite or a Meal Buddy schema change.
--
-- Depth 0 rows are top-level categories and are NOT selectable: they exist so fine selections can be
-- aggregated into the compact Meal Buddy card lines. Depth 1 rows are the selectable fine tags.
--
-- display_order is explicit and sparse (category n*100, tag n*100+i) so a future option can be
-- inserted between two existing entries without renumbering anything.
--
-- The zh-TW strings below are LABELS ONLY. Identity is tag_key; a future en or ja locale is
-- additional rows in social_interest_catalog_label and changes no identity anywhere.
--
-- PUBLIC INTEREST, NOT HEALTH DATA. food.ingredient_style.vegetarian_food and
-- food.ingredient_style.spicy_food are things a user said they enjoy. They are never a dietary
-- restriction, an allergy or a medical fact, and nothing may reinterpret them as one.

begin;

insert into public.social_interest_catalog
  (tag_key, namespace, parent_key, depth, selectable, display_order)
values
  ('general.entertainment', 'general', null, 0, false, 100),
  ('general.entertainment.movie', 'general', 'general.entertainment', 1, true, 101),
  ('general.entertainment.tv_series', 'general', 'general.entertainment', 1, true, 102),
  ('general.entertainment.anime', 'general', 'general.entertainment', 1, true, 103),
  ('general.entertainment.variety_show', 'general', 'general.entertainment', 1, true, 104),
  ('general.entertainment.theater', 'general', 'general.entertainment', 1, true, 105),
  ('general.gaming', 'general', null, 0, false, 200),
  ('general.gaming.mobile_gaming', 'general', 'general.gaming', 1, true, 201),
  ('general.gaming.pc_gaming', 'general', 'general.gaming', 1, true, 202),
  ('general.gaming.console_gaming', 'general', 'general.gaming', 1, true, 203),
  ('general.gaming.board_games', 'general', 'general.gaming', 1, true, 204),
  ('general.gaming.esports', 'general', 'general.gaming', 1, true, 205),
  ('general.fitness_sports', 'general', null, 0, false, 300),
  ('general.fitness_sports.fitness', 'general', 'general.fitness_sports', 1, true, 301),
  ('general.fitness_sports.running', 'general', 'general.fitness_sports', 1, true, 302),
  ('general.fitness_sports.hiking', 'general', 'general.fitness_sports', 1, true, 303),
  ('general.fitness_sports.swimming', 'general', 'general.fitness_sports', 1, true, 304),
  ('general.fitness_sports.ball_sports', 'general', 'general.fitness_sports', 1, true, 305),
  ('general.fitness_sports.yoga', 'general', 'general.fitness_sports', 1, true, 306),
  ('general.travel_outdoors', 'general', null, 0, false, 400),
  ('general.travel_outdoors.domestic_travel', 'general', 'general.travel_outdoors', 1, true, 401),
  ('general.travel_outdoors.overseas_travel', 'general', 'general.travel_outdoors', 1, true, 402),
  ('general.travel_outdoors.camping', 'general', 'general.travel_outdoors', 1, true, 403),
  ('general.travel_outdoors.outdoor_activities', 'general', 'general.travel_outdoors', 1, true, 404),
  ('general.travel_outdoors.city_exploration', 'general', 'general.travel_outdoors', 1, true, 405),
  ('general.music', 'general', null, 0, false, 500),
  ('general.music.listening_music', 'general', 'general.music', 1, true, 501),
  ('general.music.concerts', 'general', 'general.music', 1, true, 502),
  ('general.music.music_festival', 'general', 'general.music', 1, true, 503),
  ('general.music.instruments', 'general', 'general.music', 1, true, 504),
  ('general.music.singing', 'general', 'general.music', 1, true, 505),
  ('general.creative', 'general', null, 0, false, 600),
  ('general.creative.photography', 'general', 'general.creative', 1, true, 601),
  ('general.creative.drawing', 'general', 'general.creative', 1, true, 602),
  ('general.creative.design', 'general', 'general.creative', 1, true, 603),
  ('general.creative.writing', 'general', 'general.creative', 1, true, 604),
  ('general.creative.handicraft', 'general', 'general.creative', 1, true, 605),
  ('general.creative.video_creation', 'general', 'general.creative', 1, true, 606),
  ('general.learning_culture', 'general', null, 0, false, 700),
  ('general.learning_culture.reading', 'general', 'general.learning_culture', 1, true, 701),
  ('general.learning_culture.technology', 'general', 'general.learning_culture', 1, true, 702),
  ('general.learning_culture.history', 'general', 'general.learning_culture', 1, true, 703),
  ('general.learning_culture.museums', 'general', 'general.learning_culture', 1, true, 704),
  ('general.learning_culture.exhibitions', 'general', 'general.learning_culture', 1, true, 705),
  ('general.lifestyle_social', 'general', null, 0, false, 800),
  ('general.lifestyle_social.pets', 'general', 'general.lifestyle_social', 1, true, 801),
  ('general.lifestyle_social.shopping', 'general', 'general.lifestyle_social', 1, true, 802),
  ('general.lifestyle_social.cafes', 'general', 'general.lifestyle_social', 1, true, 803),
  ('general.lifestyle_social.karaoke', 'general', 'general.lifestyle_social', 1, true, 804),
  ('general.lifestyle_social.escape_rooms', 'general', 'general.lifestyle_social', 1, true, 805),
  ('general.lifestyle_social.social_gatherings', 'general', 'general.lifestyle_social', 1, true, 806),
  ('food.taiwanese_chinese', 'food', null, 0, false, 100),
  ('food.taiwanese_chinese.taiwanese_snacks', 'food', 'food.taiwanese_chinese', 1, true, 101),
  ('food.taiwanese_chinese.stir_fry', 'food', 'food.taiwanese_chinese', 1, true, 102),
  ('food.taiwanese_chinese.sichuan', 'food', 'food.taiwanese_chinese', 1, true, 103),
  ('food.taiwanese_chinese.hong_kong', 'food', 'food.taiwanese_chinese', 1, true, 104),
  ('food.taiwanese_chinese.hotpot', 'food', 'food.taiwanese_chinese', 1, true, 105),
  ('food.japanese', 'food', null, 0, false, 200),
  ('food.japanese.japanese_cuisine', 'food', 'food.japanese', 1, true, 201),
  ('food.japanese.sushi', 'food', 'food.japanese', 1, true, 202),
  ('food.japanese.sashimi', 'food', 'food.japanese', 1, true, 203),
  ('food.japanese.yakiniku', 'food', 'food.japanese', 1, true, 204),
  ('food.japanese.ramen', 'food', 'food.japanese', 1, true, 205),
  ('food.japanese.izakaya', 'food', 'food.japanese', 1, true, 206),
  ('food.korean', 'food', null, 0, false, 300),
  ('food.korean.korean_cuisine', 'food', 'food.korean', 1, true, 301),
  ('food.korean.korean_bbq', 'food', 'food.korean', 1, true, 302),
  ('food.korean.korean_fried_chicken', 'food', 'food.korean', 1, true, 303),
  ('food.western', 'food', null, 0, false, 400),
  ('food.western.italian', 'food', 'food.western', 1, true, 401),
  ('food.western.french', 'food', 'food.western', 1, true, 402),
  ('food.western.american', 'food', 'food.western', 1, true, 403),
  ('food.western.steak', 'food', 'food.western', 1, true, 404),
  ('food.western.pizza', 'food', 'food.western', 1, true, 405),
  ('food.western.pasta', 'food', 'food.western', 1, true, 406),
  ('food.international', 'food', null, 0, false, 500),
  ('food.international.thai', 'food', 'food.international', 1, true, 501),
  ('food.international.vietnamese', 'food', 'food.international', 1, true, 502),
  ('food.international.indian', 'food', 'food.international', 1, true, 503),
  ('food.international.mexican', 'food', 'food.international', 1, true, 504),
  ('food.international.southeast_asian', 'food', 'food.international', 1, true, 505),
  ('food.dessert_drinks', 'food', null, 0, false, 600),
  ('food.dessert_drinks.dessert', 'food', 'food.dessert_drinks', 1, true, 601),
  ('food.dessert_drinks.cake', 'food', 'food.dessert_drinks', 1, true, 602),
  ('food.dessert_drinks.ice_cream', 'food', 'food.dessert_drinks', 1, true, 603),
  ('food.dessert_drinks.coffee', 'food', 'food.dessert_drinks', 1, true, 604),
  ('food.dessert_drinks.bubble_tea', 'food', 'food.dessert_drinks', 1, true, 605),
  ('food.dessert_drinks.afternoon_tea', 'food', 'food.dessert_drinks', 1, true, 606),
  ('food.dining_style', 'food', null, 0, false, 700),
  ('food.dining_style.brunch', 'food', 'food.dining_style', 1, true, 701),
  ('food.dining_style.late_night', 'food', 'food.dining_style', 1, true, 702),
  ('food.dining_style.buffet', 'food', 'food.dining_style', 1, true, 703),
  ('food.dining_style.fine_dining', 'food', 'food.dining_style', 1, true, 704),
  ('food.dining_style.street_food', 'food', 'food.dining_style', 1, true, 705),
  ('food.ingredient_style', 'food', null, 0, false, 800),
  ('food.ingredient_style.seafood', 'food', 'food.ingredient_style', 1, true, 801),
  ('food.ingredient_style.meat_lover', 'food', 'food.ingredient_style', 1, true, 802),
  ('food.ingredient_style.vegetarian_food', 'food', 'food.ingredient_style', 1, true, 803),
  ('food.ingredient_style.cheese', 'food', 'food.ingredient_style', 1, true, 804),
  ('food.ingredient_style.spicy_food', 'food', 'food.ingredient_style', 1, true, 805);

insert into public.social_interest_catalog_label (tag_key, locale, label)
values
  ('general.entertainment', 'zh-TW', '影視娛樂'),
  ('general.entertainment.movie', 'zh-TW', '電影'),
  ('general.entertainment.tv_series', 'zh-TW', '影集'),
  ('general.entertainment.anime', 'zh-TW', '動漫'),
  ('general.entertainment.variety_show', 'zh-TW', '綜藝'),
  ('general.entertainment.theater', 'zh-TW', '舞台劇'),
  ('general.gaming', 'zh-TW', '遊戲'),
  ('general.gaming.mobile_gaming', 'zh-TW', '手遊'),
  ('general.gaming.pc_gaming', 'zh-TW', 'PC遊戲'),
  ('general.gaming.console_gaming', 'zh-TW', '主機遊戲'),
  ('general.gaming.board_games', 'zh-TW', '桌遊'),
  ('general.gaming.esports', 'zh-TW', '電競'),
  ('general.fitness_sports', 'zh-TW', '運動健身'),
  ('general.fitness_sports.fitness', 'zh-TW', '健身'),
  ('general.fitness_sports.running', 'zh-TW', '跑步'),
  ('general.fitness_sports.hiking', 'zh-TW', '登山'),
  ('general.fitness_sports.swimming', 'zh-TW', '游泳'),
  ('general.fitness_sports.ball_sports', 'zh-TW', '球類'),
  ('general.fitness_sports.yoga', 'zh-TW', '瑜伽'),
  ('general.travel_outdoors', 'zh-TW', '旅行探索'),
  ('general.travel_outdoors.domestic_travel', 'zh-TW', '國內旅行'),
  ('general.travel_outdoors.overseas_travel', 'zh-TW', '海外旅行'),
  ('general.travel_outdoors.camping', 'zh-TW', '露營'),
  ('general.travel_outdoors.outdoor_activities', 'zh-TW', '戶外活動'),
  ('general.travel_outdoors.city_exploration', 'zh-TW', '城市探索'),
  ('general.music', 'zh-TW', '音樂表演'),
  ('general.music.listening_music', 'zh-TW', '聽音樂'),
  ('general.music.concerts', 'zh-TW', '演唱會'),
  ('general.music.music_festival', 'zh-TW', '音樂祭'),
  ('general.music.instruments', 'zh-TW', '樂器'),
  ('general.music.singing', 'zh-TW', '唱歌'),
  ('general.creative', 'zh-TW', '創作'),
  ('general.creative.photography', 'zh-TW', '攝影'),
  ('general.creative.drawing', 'zh-TW', '繪畫'),
  ('general.creative.design', 'zh-TW', '設計'),
  ('general.creative.writing', 'zh-TW', '寫作'),
  ('general.creative.handicraft', 'zh-TW', '手作'),
  ('general.creative.video_creation', 'zh-TW', '影音創作'),
  ('general.learning_culture', 'zh-TW', '知識文化'),
  ('general.learning_culture.reading', 'zh-TW', '閱讀'),
  ('general.learning_culture.technology', 'zh-TW', '科技'),
  ('general.learning_culture.history', 'zh-TW', '歷史'),
  ('general.learning_culture.museums', 'zh-TW', '博物館'),
  ('general.learning_culture.exhibitions', 'zh-TW', '展覽'),
  ('general.lifestyle_social', 'zh-TW', '生活休閒'),
  ('general.lifestyle_social.pets', 'zh-TW', '寵物'),
  ('general.lifestyle_social.shopping', 'zh-TW', '逛街'),
  ('general.lifestyle_social.cafes', 'zh-TW', '咖啡廳'),
  ('general.lifestyle_social.karaoke', 'zh-TW', 'KTV'),
  ('general.lifestyle_social.escape_rooms', 'zh-TW', '密室逃脫'),
  ('general.lifestyle_social.social_gatherings', 'zh-TW', '聚會'),
  ('food.taiwanese_chinese', 'zh-TW', '台灣／中式'),
  ('food.taiwanese_chinese.taiwanese_snacks', 'zh-TW', '台灣小吃'),
  ('food.taiwanese_chinese.stir_fry', 'zh-TW', '熱炒'),
  ('food.taiwanese_chinese.sichuan', 'zh-TW', '川菜'),
  ('food.taiwanese_chinese.hong_kong', 'zh-TW', '港式'),
  ('food.taiwanese_chinese.hotpot', 'zh-TW', '火鍋'),
  ('food.japanese', 'zh-TW', '日式'),
  ('food.japanese.japanese_cuisine', 'zh-TW', '日料'),
  ('food.japanese.sushi', 'zh-TW', '壽司'),
  ('food.japanese.sashimi', 'zh-TW', '生魚片'),
  ('food.japanese.yakiniku', 'zh-TW', '燒肉'),
  ('food.japanese.ramen', 'zh-TW', '拉麵'),
  ('food.japanese.izakaya', 'zh-TW', '居酒屋'),
  ('food.korean', 'zh-TW', '韓式'),
  ('food.korean.korean_cuisine', 'zh-TW', '韓式料理'),
  ('food.korean.korean_bbq', 'zh-TW', '韓式烤肉'),
  ('food.korean.korean_fried_chicken', 'zh-TW', '韓式炸雞'),
  ('food.western', 'zh-TW', '西式'),
  ('food.western.italian', 'zh-TW', '義式'),
  ('food.western.french', 'zh-TW', '法式'),
  ('food.western.american', 'zh-TW', '美式'),
  ('food.western.steak', 'zh-TW', '牛排'),
  ('food.western.pizza', 'zh-TW', '披薩'),
  ('food.western.pasta', 'zh-TW', '義大利麵'),
  ('food.international', 'zh-TW', '異國料理'),
  ('food.international.thai', 'zh-TW', '泰式'),
  ('food.international.vietnamese', 'zh-TW', '越式'),
  ('food.international.indian', 'zh-TW', '印度料理'),
  ('food.international.mexican', 'zh-TW', '墨西哥料理'),
  ('food.international.southeast_asian', 'zh-TW', '東南亞料理'),
  ('food.dessert_drinks', 'zh-TW', '甜點飲品'),
  ('food.dessert_drinks.dessert', 'zh-TW', '甜點'),
  ('food.dessert_drinks.cake', 'zh-TW', '蛋糕'),
  ('food.dessert_drinks.ice_cream', 'zh-TW', '冰品'),
  ('food.dessert_drinks.coffee', 'zh-TW', '咖啡'),
  ('food.dessert_drinks.bubble_tea', 'zh-TW', '手搖飲'),
  ('food.dessert_drinks.afternoon_tea', 'zh-TW', '下午茶'),
  ('food.dining_style', 'zh-TW', '用餐風格'),
  ('food.dining_style.brunch', 'zh-TW', '早午餐'),
  ('food.dining_style.late_night', 'zh-TW', '宵夜'),
  ('food.dining_style.buffet', 'zh-TW', '吃到飽'),
  ('food.dining_style.fine_dining', 'zh-TW', 'Fine Dining'),
  ('food.dining_style.street_food', 'zh-TW', '街頭美食'),
  ('food.ingredient_style', 'zh-TW', '食材偏好'),
  ('food.ingredient_style.seafood', 'zh-TW', '海鮮'),
  ('food.ingredient_style.meat_lover', 'zh-TW', '肉食'),
  ('food.ingredient_style.vegetarian_food', 'zh-TW', '蔬食'),
  ('food.ingredient_style.cheese', 'zh-TW', '起司'),
  ('food.ingredient_style.spicy_food', 'zh-TW', '辛辣');

commit;
