// GQA-6R C-1: the ONE build-time Consumer public runtime configuration.
//
// Expo's web export inlines `process.env.EXPO_PUBLIC_*` only where it appears as a literal member
// expression. At runtime the exported bundle's `process.env` holds nothing but NODE_ENV, so any
// indirect read — spreading `process.env`, `globalThis.process?.env`, or dynamic indexing — resolves
// every flag to undefined in the Stable Demo even when the build environment defines it (the dev
// server happens to expose them, which is why indirect reads looked correct locally). Every Consumer
// runtime composition therefore reads its public configuration from this module, and every name
// below is referenced literally so the bundler can inline it.
//
// Values are public by definition (EXPO_PUBLIC_*); nothing secret belongs here.

type ConsumerRuntimeProcess = { env: Record<string, string | undefined> };
declare const process: ConsumerRuntimeProcess;

export const CONSUMER_PUBLIC_RUNTIME_ENV_NAMES = Object.freeze([
  "EXPO_PUBLIC_TASTKIND_ENVIRONMENT",
  "EXPO_PUBLIC_ENABLE_DEMO_TOOLS",
  "EXPO_PUBLIC_SUPABASE_URL",
  "EXPO_PUBLIC_SUPABASE_ANON_KEY",
  "EXPO_PUBLIC_TASTKIND_CONSUMER_SUPABASE_URL",
  "EXPO_PUBLIC_TASTKIND_CONSUMER_SUPABASE_PUBLISHABLE_KEY",
  "EXPO_PUBLIC_TASTKIND_CONSUMER_AUTH_SOURCE",
  "EXPO_PUBLIC_TASTKIND_CONSUMER_PROFILE_SOURCE",
  "EXPO_PUBLIC_TASTKIND_CONSUMER_SUPABASE_AUTH_ENABLED",
  "EXPO_PUBLIC_TASTKIND_CONSUMER_SUPABASE_WRITES_ENABLED",
  "EXPO_PUBLIC_TASTKIND_CONSUMER_SUPABASE_WRITES",
  "EXPO_PUBLIC_TASTKIND_CONSUMER_MEAL_RECORDS_SOURCE",
  "EXPO_PUBLIC_TASTKIND_CONSUMER_MEAL_SOURCE",
  "EXPO_PUBLIC_TASTKIND_CONSUMER_MEAL_RECORD_WRITES_ENABLED",
  "EXPO_PUBLIC_TASTKIND_CONSUMER_MEAL_RECORD_LIVE_WRITE_OPT_IN",
  "EXPO_PUBLIC_TASTKIND_CONSUMER_DAILY_NUTRITION_SOURCE",
  "EXPO_PUBLIC_TASTKIND_CONSUMER_DAILY_NUTRITION_WRITE_SOURCE",
  "EXPO_PUBLIC_TASTKIND_CONSUMER_DAILY_NUTRITION_LIVE_READ_OPT_IN",
  "EXPO_PUBLIC_TASTKIND_CONSUMER_PLANNED_MEALS_SOURCE",
  "EXPO_PUBLIC_TASTKIND_CONSUMER_PLANNED_MEALS_WRITE_SOURCE",
  "EXPO_PUBLIC_TASTKIND_CONSUMER_PLANNED_MEALS_LIVE_READ_OPT_IN",
  "EXPO_PUBLIC_TASTKIND_CONSUMER_MEAL_CORRECTION_SOURCE",
  "EXPO_PUBLIC_TASTKIND_CONSUMER_NEXT_MEAL_RECOMMENDATION_SOURCE",
  "EXPO_PUBLIC_TASTKIND_CONSUMER_RESTAURANT_CATALOG_SOURCE",
  "EXPO_PUBLIC_TASTKIND_CONSUMER_FAVORITES_READ_SOURCE",
  "EXPO_PUBLIC_TASTKIND_CONSUMER_FAVORITES_WRITE_SOURCE",
  "EXPO_PUBLIC_TASTKIND_CONSUMER_RATINGS_READ_SOURCE",
  "EXPO_PUBLIC_TASTKIND_CONSUMER_RATINGS_WRITE_SOURCE",
  "EXPO_PUBLIC_TASTKIND_CONSUMER_RECOMMENDATION_FEEDBACK_SOURCE",
  "EXPO_PUBLIC_TASTKIND_CONSUMER_MEAL_PHOTO_UPLOAD_SOURCE",
  "EXPO_PUBLIC_TASTKIND_CONSUMER_MEAL_PHOTO_ANALYSIS_SOURCE",
  "EXPO_PUBLIC_TASTKIND_CONSUMER_MEAL_IDENTIFICATION_FINALIZATION_SOURCE",
  "EXPO_PUBLIC_TASTKIND_CONSUMER_MEAL_BUDDY_CANDIDATE_SOURCE",
  "EXPO_PUBLIC_TASTKIND_CONSUMER_SOCIAL_CANDIDATE_SOURCE"
] as const);

export type ConsumerPublicRuntimeEnvName = (typeof CONSUMER_PUBLIC_RUNTIME_ENV_NAMES)[number];
export type ConsumerPublicRuntimeEnv = Readonly<
  Partial<Record<ConsumerPublicRuntimeEnvName | "TASTKIND_ENVIRONMENT" | "NODE_ENV", string>> &
  Record<string, string | undefined>
>;

// Every entry is a literal `process.env.<NAME>` member so the web export inlines it. Keep this list
// and CONSUMER_PUBLIC_RUNTIME_ENV_NAMES identical (scripts/gqa6r-consumer-runtime-config-guard.mjs).
export function readConsumerPublicRuntimeEnv(): ConsumerPublicRuntimeEnv {
  return Object.freeze({
    EXPO_PUBLIC_TASTKIND_ENVIRONMENT: process.env.EXPO_PUBLIC_TASTKIND_ENVIRONMENT,
    EXPO_PUBLIC_ENABLE_DEMO_TOOLS: process.env.EXPO_PUBLIC_ENABLE_DEMO_TOOLS,
    EXPO_PUBLIC_SUPABASE_URL: process.env.EXPO_PUBLIC_SUPABASE_URL,
    EXPO_PUBLIC_SUPABASE_ANON_KEY: process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY,
    EXPO_PUBLIC_TASTKIND_CONSUMER_SUPABASE_URL: process.env.EXPO_PUBLIC_TASTKIND_CONSUMER_SUPABASE_URL,
    EXPO_PUBLIC_TASTKIND_CONSUMER_SUPABASE_PUBLISHABLE_KEY: process.env.EXPO_PUBLIC_TASTKIND_CONSUMER_SUPABASE_PUBLISHABLE_KEY,
    EXPO_PUBLIC_TASTKIND_CONSUMER_AUTH_SOURCE: process.env.EXPO_PUBLIC_TASTKIND_CONSUMER_AUTH_SOURCE,
    EXPO_PUBLIC_TASTKIND_CONSUMER_PROFILE_SOURCE: process.env.EXPO_PUBLIC_TASTKIND_CONSUMER_PROFILE_SOURCE,
    EXPO_PUBLIC_TASTKIND_CONSUMER_SUPABASE_AUTH_ENABLED: process.env.EXPO_PUBLIC_TASTKIND_CONSUMER_SUPABASE_AUTH_ENABLED,
    EXPO_PUBLIC_TASTKIND_CONSUMER_SUPABASE_WRITES_ENABLED: process.env.EXPO_PUBLIC_TASTKIND_CONSUMER_SUPABASE_WRITES_ENABLED,
    EXPO_PUBLIC_TASTKIND_CONSUMER_SUPABASE_WRITES: process.env.EXPO_PUBLIC_TASTKIND_CONSUMER_SUPABASE_WRITES,
    EXPO_PUBLIC_TASTKIND_CONSUMER_MEAL_RECORDS_SOURCE: process.env.EXPO_PUBLIC_TASTKIND_CONSUMER_MEAL_RECORDS_SOURCE,
    EXPO_PUBLIC_TASTKIND_CONSUMER_MEAL_SOURCE: process.env.EXPO_PUBLIC_TASTKIND_CONSUMER_MEAL_SOURCE,
    EXPO_PUBLIC_TASTKIND_CONSUMER_MEAL_RECORD_WRITES_ENABLED: process.env.EXPO_PUBLIC_TASTKIND_CONSUMER_MEAL_RECORD_WRITES_ENABLED,
    EXPO_PUBLIC_TASTKIND_CONSUMER_MEAL_RECORD_LIVE_WRITE_OPT_IN: process.env.EXPO_PUBLIC_TASTKIND_CONSUMER_MEAL_RECORD_LIVE_WRITE_OPT_IN,
    EXPO_PUBLIC_TASTKIND_CONSUMER_DAILY_NUTRITION_SOURCE: process.env.EXPO_PUBLIC_TASTKIND_CONSUMER_DAILY_NUTRITION_SOURCE,
    EXPO_PUBLIC_TASTKIND_CONSUMER_DAILY_NUTRITION_WRITE_SOURCE: process.env.EXPO_PUBLIC_TASTKIND_CONSUMER_DAILY_NUTRITION_WRITE_SOURCE,
    EXPO_PUBLIC_TASTKIND_CONSUMER_DAILY_NUTRITION_LIVE_READ_OPT_IN: process.env.EXPO_PUBLIC_TASTKIND_CONSUMER_DAILY_NUTRITION_LIVE_READ_OPT_IN,
    EXPO_PUBLIC_TASTKIND_CONSUMER_PLANNED_MEALS_SOURCE: process.env.EXPO_PUBLIC_TASTKIND_CONSUMER_PLANNED_MEALS_SOURCE,
    EXPO_PUBLIC_TASTKIND_CONSUMER_PLANNED_MEALS_WRITE_SOURCE: process.env.EXPO_PUBLIC_TASTKIND_CONSUMER_PLANNED_MEALS_WRITE_SOURCE,
    EXPO_PUBLIC_TASTKIND_CONSUMER_PLANNED_MEALS_LIVE_READ_OPT_IN: process.env.EXPO_PUBLIC_TASTKIND_CONSUMER_PLANNED_MEALS_LIVE_READ_OPT_IN,
    EXPO_PUBLIC_TASTKIND_CONSUMER_MEAL_CORRECTION_SOURCE: process.env.EXPO_PUBLIC_TASTKIND_CONSUMER_MEAL_CORRECTION_SOURCE,
    EXPO_PUBLIC_TASTKIND_CONSUMER_NEXT_MEAL_RECOMMENDATION_SOURCE: process.env.EXPO_PUBLIC_TASTKIND_CONSUMER_NEXT_MEAL_RECOMMENDATION_SOURCE,
    EXPO_PUBLIC_TASTKIND_CONSUMER_RESTAURANT_CATALOG_SOURCE: process.env.EXPO_PUBLIC_TASTKIND_CONSUMER_RESTAURANT_CATALOG_SOURCE,
    EXPO_PUBLIC_TASTKIND_CONSUMER_FAVORITES_READ_SOURCE: process.env.EXPO_PUBLIC_TASTKIND_CONSUMER_FAVORITES_READ_SOURCE,
    EXPO_PUBLIC_TASTKIND_CONSUMER_FAVORITES_WRITE_SOURCE: process.env.EXPO_PUBLIC_TASTKIND_CONSUMER_FAVORITES_WRITE_SOURCE,
    EXPO_PUBLIC_TASTKIND_CONSUMER_RATINGS_READ_SOURCE: process.env.EXPO_PUBLIC_TASTKIND_CONSUMER_RATINGS_READ_SOURCE,
    EXPO_PUBLIC_TASTKIND_CONSUMER_RATINGS_WRITE_SOURCE: process.env.EXPO_PUBLIC_TASTKIND_CONSUMER_RATINGS_WRITE_SOURCE,
    EXPO_PUBLIC_TASTKIND_CONSUMER_RECOMMENDATION_FEEDBACK_SOURCE: process.env.EXPO_PUBLIC_TASTKIND_CONSUMER_RECOMMENDATION_FEEDBACK_SOURCE,
    EXPO_PUBLIC_TASTKIND_CONSUMER_MEAL_PHOTO_UPLOAD_SOURCE: process.env.EXPO_PUBLIC_TASTKIND_CONSUMER_MEAL_PHOTO_UPLOAD_SOURCE,
    EXPO_PUBLIC_TASTKIND_CONSUMER_MEAL_PHOTO_ANALYSIS_SOURCE: process.env.EXPO_PUBLIC_TASTKIND_CONSUMER_MEAL_PHOTO_ANALYSIS_SOURCE,
    EXPO_PUBLIC_TASTKIND_CONSUMER_MEAL_IDENTIFICATION_FINALIZATION_SOURCE: process.env.EXPO_PUBLIC_TASTKIND_CONSUMER_MEAL_IDENTIFICATION_FINALIZATION_SOURCE,
    EXPO_PUBLIC_TASTKIND_CONSUMER_MEAL_BUDDY_CANDIDATE_SOURCE: process.env.EXPO_PUBLIC_TASTKIND_CONSUMER_MEAL_BUDDY_CANDIDATE_SOURCE,
    EXPO_PUBLIC_TASTKIND_CONSUMER_SOCIAL_CANDIDATE_SOURCE: process.env.EXPO_PUBLIC_TASTKIND_CONSUMER_SOCIAL_CANDIDATE_SOURCE,
    // Non-public build inputs some compositions already consult; never inlined into a web bundle.
    TASTKIND_ENVIRONMENT: typeof process === "undefined" ? undefined : process.env.TASTKIND_ENVIRONMENT,
    NODE_ENV: typeof process === "undefined" ? undefined : process.env.NODE_ENV
  });
}

// C-1B fail-closed rule. A LIVE Consumer composition is one whose identity is a real Supabase session
// (EXPO_PUBLIC_TASTKIND_CONSUMER_AUTH_SOURCE=supabase-live). In a live composition a data source whose
// flag is missing must resolve to disabled/unavailable — never to mock fixtures — because real user
// state must never be combined with invented data. Outside a live composition (no live identity at all:
// local demo preview, harnesses) the historical defaults are unchanged. An EXPLICIT "mock" value remains
// an explicit, auditable choice.
export function isLiveConsumerComposition(env: Readonly<Record<string, string | undefined>>): boolean {
  return env.EXPO_PUBLIC_TASTKIND_CONSUMER_AUTH_SOURCE === "supabase-live";
}

export function allowsImplicitMockSource(env: Readonly<Record<string, string | undefined>>): boolean {
  return !isLiveConsumerComposition(env);
}
